n0: "No"
n1: "No"
y0: "Yes"
y1: "Yes"
y2: "Yes"

Outlook -> Humidity : Sunny
Outlook -> y0 : Overcast
Outlook -> Wind : Rain
Humidity -> n0 : High
Humidity -> y1 : Normal
Wind -> n1 : Strong
Wind -> y2 : Weak
