@startuml

class ProductCatalog {
    + findProductDescription(item)
    - productDatabase : IProductDatabase
}

class IProductDatabase {
    + findProductDescription(item)
}

class ProductDatabaseProxy {
    - realProductDatabase : IProductDatabase
    + findProductDescription(item)
}

class RealProductDatabase {
    + findProductDescription(item)
}

ProductCatalog ---> IProductDatabase
ProductDatabaseProxy ---> IProductDatabase
ProductDatabaseProxy --|> IProductDatabase
RealProductDatabase --|> IProductDatabase

@enduml
