"M_2" -> "caffe . M_2 + coin . tea . M_2" : coin
"caffe . M_2 + coin . tea . M_2" -> "M_2" : caffe
"M_2" -> "coin . tea . M_2" : coin
"coin . tea . M_2" -> "tea . M_2" : coin
"tea . M_2" -> "M_2" : tea
